Assignment Report:



                                CLASSIFICATION DATASET REPORT
First we have my Classification Dataset, which is my weather classification data, in which we have been given a mix of categorical and numerical variable types including temperature, humidity, wind speed etc. My objective was to first clean the Dataset which was done by first loading the data, and then displaying a few rows by using our .head() function. I then proceeded to remove the missing values, but first i actually found out how many nan values are there in the dataset. When i calculated the nan values of the dataset using .isnull().sum() function, i found out that there are no nan values present. Proceeding, i converted my categorical values to numerical values. I first made a list consisting of my categorical values, and then applied one hot encoding to the dataset in order to convert into a completely numerical dataset. After converting, i normalized the dataset. After this, i split the the datset into training and testing variables and then calculated the mean,mode and median of the normalized dataset. I then proceeded to visualize he dataset, but I was having trouble with import matplotlib, it was upgrading the necssary things, due to which i was constantly getting errors. I then moved on to apply algorithms, which i have explained in comments below.



                              REGRESSION DATASET REPORT
                              
For my regression dataset, i had two datasets which i cleaned and visualized seperately. I first loaded each dataset and the proceeded to display a few rows of each dataset. I then calculated my missing values in my dataset. Since there were a large number of missing values in the dataset, i chose to remove the missing data, instead of filling it by mean/median/mode which could ruin the dataset. After doing this, i converted my categorical values to numerical values and then normalized the dataset. Finally i calculated the mena, median, mdoe of the noralized dataste and then used matplotlib to visualzie the data.

# Preprocessing and Cleaning the Dataset

In [2]:
import pandas as pd

In [3]:
#loading the first data set


df1 = pd.read_csv(r"C:\Users\HP\Downloads\weather_classification_data.csv")
df1

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27.0,74,17.0,66.0,overcast,990.67,1,Winter,2.5,mountain,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,overcast,1003.15,1,Summer,1.0,mountain,Rainy
13196,-1.0,76,3.5,23.0,cloudy,1067.23,1,Winter,6.0,coastal,Snowy
13197,30.0,77,5.5,28.0,overcast,1012.69,3,Autumn,9.0,coastal,Cloudy
13198,3.0,76,10.0,94.0,overcast,984.27,0,Winter,2.0,inland,Snowy
13199,-5.0,38,0.0,92.0,overcast,1015.37,5,Autumn,10.0,mountain,Rainy

In [4]:
#displaying its first 15 rows

df1.head(15)

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27.0,74,17.0,66.0,overcast,990.67,1,Winter,2.5,mountain,Rainy
5,32.0,55,3.5,26.0,overcast,1010.03,2,Summer,5.0,inland,Cloudy
6,-2.0,97,8.0,86.0,overcast,990.87,1,Winter,4.0,inland,Snowy
7,3.0,85,6.0,96.0,partly cloudy,984.46,1,Winter,3.5,inland,Snowy
8,3.0,83,6.0,66.0,overcast,999.44,0,Winter,1.0,mountain,Snowy
9,28.0,74,8.5,107.0,clear,1012.13,8,Winter,7.5,coastal,Sunny
10,35.0,45,6.0,86.0,partly cloudy,879.88,2,Spring,1.0,mountain,Cloudy
11,38.0,43,2.0,16.0,clear,1029.16,11,Autumn,7.5,inland,Sunny
12,12.0,59,10.5,25.0,partly cloudy,1016.08,3,Autumn,5.5,mountain,Cloudy
13,-10.0,87,15.0,67.0,overcast,986.19,0,Winter,1.5,inland,Snowy
14,24.0,21,3.5,8.0,clear,1018.88,8,Winter,5.5,coastal,Sunny

In [5]:
#next first i decided to find out how many missing values are there in the data set


missing_values = df1.isnull().sum()
print("Missing values per column:")
print(missing_values[missing_values > 0])

Missing values per column:
Series([], dtype: int64)

In [6]:
#since there are no missing values, i then proceeded to convert categorical data to numerical data



#first i made a list of all of my categorical columns, by comparing with the csv file
categorical_columns = ['Cloud Cover', 'Season', 'Location', 'Weather Type']

# the i applied one-hot encoding to the categorical columns
df1_one_hot = pd.get_dummies(df1, columns=categorical_columns)


print("Dataset after applying One-Hot Encoding :")
df1_one_hot.head(14)

Dataset after applying One-Hot Encoding :

,Temperature,Humidity,Wind Speed,Precipitation (%),Atmospheric Pressure,UV Index,Visibility (km),Cloud Cover_clear,Cloud Cover_cloudy,Cloud Cover_overcast,...,Season_Spring,Season_Summer,Season_Winter,Location_coastal,Location_inland,Location_mountain,Weather Type_Cloudy,Weather Type_Rainy,Weather Type_Snowy,Weather Type_Sunny
0,14.0,73,9.5,82.0,1010.82,2,3.5,False,False,False,...,False,False,True,False,True,False,False,True,False,False
1,39.0,96,8.5,71.0,1011.43,7,10.0,False,False,False,...,True,False,False,False,True,False,True,False,False,False
2,30.0,64,7.0,16.0,1018.72,5,5.5,True,False,False,...,True,False,False,False,False,True,False,False,False,True
3,38.0,83,1.5,82.0,1026.25,7,1.0,True,False,False,...,True,False,False,True,False,False,False,False,False,True
4,27.0,74,17.0,66.0,990.67,1,2.5,False,False,True,...,False,False,True,False,False,True,False,True,False,False
5,32.0,55,3.5,26.0,1010.03,2,5.0,False,False,True,...,False,True,False,False,True,False,True,False,False,False
6,-2.0,97,8.0,86.0,990.87,1,4.0,False,False,True,...,False,False,True,False,True,False,False,False,True,False
7,3.0,85,6.0,96.0,984.46,1,3.5,False,False,False,...,False,False,True,False,True,False,False,False,True,False
8,3.0,83,6.0,66.0,999.44,0,1.0,False,False,True,...,False,False,True,False,False,True,False,False,True,False
9,28.0,74,8.5,107.0,1012.13,8,7.5,True,False,False,...,False,False,True,True,False,False,False,False,False,True
10,35.0,45,6.0,86.0,879.88,2,1.0,False,False,False,...,True,False,False,False,False,True,True,False,False,False
11,38.0,43,2.0,16.0,1029.16,11,7.5,True,False,False,...,False,False,False,False,True,False,False,False,False,True
12,12.0,59,10.5,25.0,1016.08,3,5.5,False,False,False,...,False,False,False,False,False,True,True,False,False,False
13,-10.0,87,15.0,67.0,986.19,0,1.5,False,False,True,...,False,False,True,False,True,False,False,False,True,False

In [7]:
import pandas as pd

#now after applying one hot encoding to my data set, i first identified the numerical columns and then normalized them


numerical_columns = df1_one_hot.select_dtypes(include=['int64', 'float64']).columns

df1_normalized = df1_one_hot.copy()
df1_normalized[numerical_columns] = (df1_one_hot[numerical_columns] - df1_one_hot[numerical_columns].min()) / (df1_one_hot[numerical_columns].max() - df1_one_hot[numerical_columns].min())

print("Normalized DataFrame (first 5 rows):")
df1_normalized.head(14)

Normalized DataFrame (first 5 rows):

,Temperature,Humidity,Wind Speed,Precipitation (%),Atmospheric Pressure,UV Index,Visibility (km),Cloud Cover_clear,Cloud Cover_cloudy,Cloud Cover_overcast,...,Season_Spring,Season_Summer,Season_Winter,Location_coastal,Location_inland,Location_mountain,Weather Type_Cloudy,Weather Type_Rainy,Weather Type_Snowy,Weather Type_Sunny
0,0.291045,0.595506,0.195876,0.752294,0.527951,0.142857,0.175,False,False,False,...,False,False,True,False,True,False,False,True,False,False
1,0.477612,0.853933,0.175258,0.651376,0.529480,0.500000,0.500,False,False,False,...,True,False,False,False,True,False,True,False,False,False
2,0.410448,0.494382,0.144330,0.146789,0.547746,0.357143,0.275,True,False,False,...,True,False,False,False,False,True,False,False,False,True
3,0.470149,0.707865,0.030928,0.752294,0.566614,0.500000,0.050,True,False,False,...,True,False,False,True,False,False,False,False,False,True
4,0.388060,0.606742,0.350515,0.605505,0.477461,0.071429,0.125,False,False,True,...,False,False,True,False,False,True,False,True,False,False
5,0.425373,0.393258,0.072165,0.238532,0.525972,0.142857,0.250,False,False,True,...,False,True,False,False,True,False,True,False,False,False
6,0.171642,0.865169,0.164948,0.788991,0.477962,0.071429,0.200,False,False,True,...,False,False,True,False,True,False,False,False,True,False
7,0.208955,0.730337,0.123711,0.880734,0.461901,0.071429,0.175,False,False,False,...,False,False,True,False,True,False,False,False,True,False
8,0.208955,0.707865,0.123711,0.605505,0.499436,0.000000,0.050,False,False,True,...,False,False,True,False,False,True,False,False,True,False
9,0.395522,0.606742,0.175258,0.981651,0.531234,0.571429,0.375,True,False,False,...,False,False,True,True,False,False,False,False,False,True
10,0.447761,0.280899,0.123711,0.788991,0.199855,0.142857,0.050,False,False,False,...,True,False,False,False,False,True,True,False,False,False
11,0.470149,0.258427,0.041237,0.146789,0.573906,0.785714,0.375,True,False,False,...,False,False,False,False,True,False,False,False,False,True
12,0.276119,0.438202,0.216495,0.229358,0.541131,0.214286,0.275,False,False,False,...,False,False,False,False,False,True,True,False,False,False
13,0.111940,0.752809,0.309278,0.614679,0.466236,0.000000,0.075,False,False,True,...,False,False,True,False,True,False,False,False,True,False

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split

#i then merged all the weather type columns, into a single weather type column so that i could later drop the other columns
df1_one_hot['Weather Type'] = df1_one_hot[['Weather Type_Cloudy', 'Weather Type_Rainy', 'Weather Type_Snowy', 'Weather Type_Sunny']].idxmax(axis=1)

X = df1_one_hot.drop(columns=['Weather Type', 'Weather Type_Cloudy', 'Weather Type_Rainy', 'Weather Type_Snowy', 'Weather Type_Sunny'])
y = df1_one_hot['Weather Type']

#i split the data into my training and testing dataset and then displayed the result
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training feature set shape: {X_train.shape}")
print(f"Test feature set shape: {X_test.shape}")
print(f"Training target set shape: {y_train.shape}")
print(f"Test target set shape: {y_test.shape}")

Training feature set shape: (10560, 18)
Test feature set shape: (2640, 18)
Training target set shape: (10560,)
Test target set shape: (2640,)

# Displaying and Visualizing Dataset

In [9]:
#calculated mean, median , mode

mean_values = df1_normalized.mean()


median_values = df1_normalized.median()

mode_values = df1_normalized.mode().iloc[0]  

#displaying the results of mean,median,mode
print("Mean values for numerical columns:")
print(mean_values)

print("\nMedian values for numerical columns:")
print(median_values)

print("\nMode values for numerical columns:")
print(mode_values)

Mean values for numerical columns:
Temperature                  0.329310
Humidity                     0.547313
Wind Speed                   0.202726
Precipitation (%)            0.492150
Atmospheric Pressure         0.515442
UV Index                     0.286126
Visibility (km)              0.273146
Cloud Cover_clear            0.162045
Cloud Cover_cloudy           0.031136
Cloud Cover_overcast         0.461364
Cloud Cover_partly cloudy    0.345455
Season_Autumn                0.189394
Season_Spring                0.196818
Season_Summer                0.188788
Season_Winter                0.425000
Location_coastal             0.270530
Location_inland              0.364848
Location_mountain            0.364621
Weather Type_Cloudy          0.250000
Weather Type_Rainy           0.250000
Weather Type_Snowy           0.250000
Weather Type_Sunny           0.250000
dtype: float64

Median values for numerical columns:
Temperature                  0.343284
Humidity                     0.561798
Wind Speed                   0.185567
Precipitation (%)            0.532110
Atmospheric Pressure         0.520008
UV Index                     0.214286
Visibility (km)              0.250000
Cloud Cover_clear            0.000000
Cloud Cover_cloudy           0.000000
Cloud Cover_overcast         0.000000
Cloud Cover_partly cloudy    0.000000
Season_Autumn                0.000000
Season_Spring                0.000000
Season_Summer                0.000000
Season_Winter                0.000000
Location_coastal             0.000000
Location_inland              0.000000
Location_mountain            0.000000
Weather Type_Cloudy          0.000000
Weather Type_Rainy           0.000000
Weather Type_Snowy           0.000000
Weather Type_Sunny           0.000000
dtype: float64

Mode values for numerical columns:
Temperature                  0.425373
Humidity                     0.629213
Wind Speed                   0.164948
Precipitation (%)            0.174312
Atmospheric Pressure         0.534842
UV Index                     0.071429
Visibility (km)                 0.075
Cloud Cover_clear               False
Cloud Cover_cloudy              False
Cloud Cover_overcast            False
Cloud Cover_partly cloudy       False
Season_Autumn                   False
Season_Spring                   False
Season_Summer                   False
Season_Winter                   False
Location_coastal                False
Location_inland                 False
Location_mountain               False
Weather Type_Cloudy             False
Weather Type_Rainy              False
Weather Type_Snowy              False
Weather Type_Sunny              False
Name: 0, dtype: object

Something was wrong with importing matplotlib, due to which i could not visualize the data. However i wrote the code in hope that it is correct.

In [ ]:
pip install matplotlib

In [ ]:
pip install --upgrade numpy
pip install --upgrade cycler
pip install --upgrade pillow
pip install --upgrade pyparsing
pip install --upgrade kiwisolver
pip install --upgrade packaging

In [ ]:
pip show matplotlib

In [ ]:
import matplotlib.pyplot as plt

In [ ]:

#plotting my histogram
df1_normalized.hist(figsize=(12, 8), bins=30, edgecolor='black')

#displaying using .show()
plt.show()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

df = df2_normalized2


#i listed the pairs of features
feature_pairs = [
    ('Temperature', 'Humidity'),
    ('Temperature', 'Wind Speed'),
    ('Temperature', 'Precipitation (%)'),
    ('Temperature', 'Atmospheric Pressure'),
    ('Temperature', 'UV Index'),
    ('Temperature', 'Visibility (km)'),
    ('Humidity', 'Wind Speed'),
    ('Humidity', 'Precipitation (%)'),
    ('Humidity', 'Atmospheric Pressure'),
    ('Humidity', 'UV Index'),
    ('Humidity', 'Visibility (km)'),
]


    #and then created subplots
plt.figure(figsize=(14, 10))
for i, (feature1, feature2) in enumerate(feature_pairs, 1):
    plt.subplot(4, 3, i) 
    plt.scatter(df[feature1], df[feature2], alpha=0.7)
    plt.title(f'Scatter Plot: {feature1} vs {feature2}')
    plt.xlabel(feature1)
    plt.ylabel(feature2)

plt.tight_layout()
plt.show()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np




corr_matrix = df1_normalized.corr()


plt.figure(figsize=(12, 10))
cax = plt.matshow(corr_matrix, cmap='coolwarm', vmin=-1, vmax=1)
plt.colorbar(cax)


plt.xticks(ticks=np.arange(len(corr_matrix.columns)), labels=corr_matrix.columns, rotation=90)
plt.yticks(ticks=np.arange(len(corr_matrix.columns)), labels=corr_matrix.columns)


plt.title('Correlation Heatmap')


plt.show()

applying and training models was a bit difficult, im not sure if i applied them correctly

In [21]:
        #i first imported all of the necessary libraries
    
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

#i then standardized the data, this was done so that the values of the input are similar, so that the performance of the model is high.
scaler = StandardScaler()
        #transforming the training and testing data

#i then trained the data using x_train and y_train which i had calculated earlier
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

y_pred = log_reg.predict(X_test)


#i then intialized the model
log_reg = LogisticRegression(max_iter=1000)
#and procedded to train it by passing the training as parameters
log_reg.fit(X_train, y_train)




print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred))
print("Logistic Regression Classification Report:\n", classification_report(y_test, y_pred))

Logistic Regression Accuracy: 0.8712121212121212
Logistic Regression Classification Report:
                      precision    recall  f1-score   support

Weather Type_Cloudy       0.82      0.84      0.83       651
 Weather Type_Rainy       0.86      0.84      0.85       647
 Weather Type_Snowy       0.89      0.94      0.91       701
 Weather Type_Sunny       0.92      0.86      0.89       641

           accuracy                           0.87      2640
          macro avg       0.87      0.87      0.87      2640
       weighted avg       0.87      0.87      0.87      2640

In [22]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
    #intializing and training the models

decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(X_train, y_train)


print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred))
print("Decision Tree Classification Report:\n", classification_report(y_test, y_pred))

Decision Tree Accuracy: 0.8712121212121212
Decision Tree Classification Report:
                      precision    recall  f1-score   support

Weather Type_Cloudy       0.82      0.84      0.83       651
 Weather Type_Rainy       0.86      0.84      0.85       647
 Weather Type_Snowy       0.89      0.94      0.91       701
 Weather Type_Sunny       0.92      0.86      0.89       641

           accuracy                           0.87      2640
          macro avg       0.87      0.87      0.87      2640
       weighted avg       0.87      0.87      0.87      2640

In [23]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

        #intializing and training the models
random_forest = RandomForestClassifier(n_estimators=100, random_state=42)
random_forest.fit(X_train, y_train)


print("Random Forest Accuracy:", accuracy_score(y_test, y_pred))
print("Random Forest Classification Report:\n", classification_report(y_test, y_pred))

Random Forest Accuracy: 0.8712121212121212
Random Forest Classification Report:
                      precision    recall  f1-score   support

Weather Type_Cloudy       0.82      0.84      0.83       651
 Weather Type_Rainy       0.86      0.84      0.85       647
 Weather Type_Snowy       0.89      0.94      0.91       701
 Weather Type_Sunny       0.92      0.86      0.89       641

           accuracy                           0.87      2640
          macro avg       0.87      0.87      0.87      2640
       weighted avg       0.87      0.87      0.87      2640

In [25]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report


#now since i had already trained my models, i moved on to evaluating my models
def evaluate_model(model, model_name):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred, output_dict=True)
    return {
        'Model': model_name,
        'Accuracy': accuracy,
        'Precision': report['weighted avg']['precision'],
        'Recall': report['weighted avg']['recall'],
        'F1-Score': report['weighted avg']['f1-score']
    }


            #i then intialized my models, and then created an empty list
log_reg = LogisticRegression(max_iter=1000)
decision_tree = DecisionTreeClassifier(random_state=42)
random_forest = RandomForestClassifier(random_state=42)


            #after creating list, i evaluated all 3 models by calling the function, and appended the results to my list
results = []
results.append(evaluate_model(log_reg, "Logistic Regression"))
results.append(evaluate_model(decision_tree, "Decision Tree"))
results.append(evaluate_model(random_forest, "Random Forest"))

        #i then converted my list into a dataframe and printed the resukt
results_df = pd.DataFrame(results)


results_df

                 Model  Accuracy  Precision    Recall  F1-Score
0  Logistic Regression  0.871212   0.872165  0.871212  0.871105
1        Decision Tree  0.908333   0.908378  0.908333  0.908292
2        Random Forest  0.914015   0.914650  0.914015  0.914153